import { DISCOVERY_AGENT_CONTRACT, DISTILLERY_ENGINE_LABEL } from './ai-orchestration';
import { DiscoveryModel } from './discovery-model';

export const discoveryModel: DiscoveryModel = {
  packageName: 'Discovery_Action_Pack',
  processName: "Uncle Kev's Distillery",
  businessFunction: 'Small-batch data discovery, lineage proofing, documentation, and engineering actioning',
  recommendation: 'Drop messy databases, Excel files, docs, SQL, exports, and notes into the still. Uncle Kev distills the evidence into one canonical graph, then generates reports, lineage, diagrams, impact, and remediation actions from that single proof model.',
  decisionRequired: 'Select the mash bill, run analysis, review unresolved blockers, and approve modernization actions for ingestion, modeling, automation, governance, or retirement.',
  systemsInScope: ['Access / ACCDB exports', 'Excel / XLSX / XLSM', 'CSV / TSV / flat files', 'SQL / database extracts', 'Word / process docs', 'Interview notes'],
  criticalOutputs: ['Executive decision brief', 'Current-state architecture report', 'Technical discovery workbook', 'Diagram pack', 'Action backlog'],
  overallRiskRating: 'high',
  estimatedDollarExposure: {
    low: 0,
    base: 0,
    high: 0,
    assumptions: 'Impact is calculated per executed discovery run from availability, quality, auditability, manual recovery, and business-process dependency evidence.'
  },
  items: [
    {
      id: 'SRC-001',
      type: 'file',
      name: 'Mash Bill Source Set',
      businessPurpose: 'Represents the files, folders, exports, documents, or extracts loaded into Uncle Kev\'s still for discovery execution.',
      owner: 'Source owner',
      evidence: [
        {
          id: 'EV-SRC-001',
          type: 'Profile',
          location: 'Browser-selected file set',
          description: 'File names, sizes, extensions, readable extraction status, and evidence payload generated by source intake.'
        }
      ],
      confidence: 85,
      criticality: 'critical',
      upstream: [],
      downstream: ['GRAPH-001', 'PACK-001'],
      failureImpact: 'If the source set is incomplete, lineage, documentation, and action recommendations will miss dependencies or blockers.',
      dollarExposure: {
        low: 0,
        base: 0,
        high: 0,
        assumptions: 'Priced only when source evidence includes business-volume, SLA, labor, compliance, or customer-impact signals.'
      },
      recommendedAction: {
        mode: 'govern',
        summary: 'Confirm the mash bill includes all known databases, files, workbooks, docs, exports, scripts, and interview notes before bottling the pack.',
        owner: 'Discovery lead',
        priority: 'P0',
        acceptanceCriteria: 'Every critical output has an inspected source, documented blocker, or approved stopping point.'
      },
      status: 'partial',
      tags: ['source-browser', 'evidence', 'scope']
    },
    {
      id: 'GRAPH-001',
      type: 'output',
      name: 'Proof-Grade Discovery Graph',
      businessPurpose: 'Single node-edge discovery model that drives documentation, diagrams, lineage, impact, and backlog outputs.',
      owner: 'Data architecture',
      evidence: [
        {
          id: 'EV-GRAPH-001',
          type: 'Profile',
          location: 'Still run synthesis response',
          description: 'Generated canonical items, relationships, evidence, confidence, impact, and actions.'
        }
      ],
      confidence: 82,
      criticality: 'critical',
      upstream: ['SRC-001'],
      downstream: ['PACK-001', 'ACT-001'],
      failureImpact: 'If the graph is incomplete, every generated artifact loses traceability and engineering teams receive weak actions.',
      dollarExposure: {
        low: 0,
        base: 0,
        high: 0,
        assumptions: 'Impact is inherited from discovered critical outputs and failure modes.'
      },
      recommendedAction: {
        mode: 'automate',
        summary: 'Save every still run, graph node, relationship, artifact, and backlog item to the workspace for review and reuse.',
        owner: 'Platform engineering',
        priority: 'P0',
        acceptanceCriteria: 'Runs can be retrieved with items, edges, artifacts, and actions intact.'
      },
      status: 'partial',
      tags: ['canonical-model', 'lineage', 'workspace']
    },
    {
      id: 'PACK-001',
      type: 'report',
      name: 'Discovery Action Pack',
      businessPurpose: 'Generated output package for leaders, architects, engineers, analysts, and governance reviewers.',
      owner: 'Discovery lead',
      evidence: [
        {
          id: 'EV-PACK-001',
          type: 'Document_Extract',
          location: 'Generated artifact cockpit',
          description: 'Reports, workbook structures, diagrams, impact outputs, backlog, evidence archive, and metadata manifest.'
        }
      ],
      confidence: 80,
      criticality: 'high',
      upstream: ['GRAPH-001'],
      downstream: [],
      failureImpact: 'Teams cannot execute modernization confidently without a concise report and traceable technical depth underneath.',
      dollarExposure: {
        low: 0,
        base: 0,
        high: 0,
        assumptions: 'Impact is scenario-based and source-specific.'
      },
      recommendedAction: {
        mode: 'migrate',
        summary: 'Generate the action pack from the canonical graph and route unresolved blockers back into source intake.',
        owner: 'Delivery lead',
        priority: 'P1',
        acceptanceCriteria: 'Every artifact references graph IDs, evidence IDs, confidence, owner, and next action.'
      },
      status: 'partial',
      tags: ['artifacts', 'reports', 'backlog']
    }
  ],
  relationships: [
    {
      id: 'EDGE-001',
      fromId: 'SRC-001',
      toId: 'GRAPH-001',
      type: 'transforms',
      automated: true,
      cadence: 'On execution',
      confidence: 84,
      evidenceId: 'EV-SRC-001'
    },
    {
      id: 'EDGE-002',
      fromId: 'GRAPH-001',
      toId: 'PACK-001',
      type: 'writes_to',
      automated: true,
      cadence: 'On execution',
      confidence: 80,
      evidenceId: 'EV-GRAPH-001'
    }
  ],
  artifacts: [
    { id: '01', name: '01_Executive_Decision_Brief.pdf', audience: 'Leadership', purpose: 'Purpose, scope, risk posture, confidence, blockers, impact, and decisions needed.', progress: 0, sourceModel: 'canonical graph' },
    { id: '02', name: '02_Current_State_Architecture_Report.pdf', audience: 'Business + IT', purpose: 'Concise evidence-backed current-state narrative.', progress: 0, sourceModel: 'canonical graph' },
    { id: '03', name: '03_Technical_Discovery_Workbook.xlsx', audience: 'Engineers / analysts', purpose: 'Structured inventory of objects, logic, lineage, risks, and actions.', progress: 0, sourceModel: 'canonical graph' },
    { id: '04', name: '04_Auto_Documentation_Pack', audience: 'Automation / governance', purpose: 'Machine-readable current-state documentation.', progress: 0, sourceModel: 'canonical graph' },
    { id: '05', name: '05_Diagram_Pack', audience: 'All audiences', purpose: 'Process, data flow, lineage, dependency, control, failure, and timeline diagrams.', progress: 0, sourceModel: 'canonical graph' },
    { id: '06', name: '06_Financial_Impact_Model.xlsx', audience: 'Leadership / operations', purpose: 'Scenario-based dollar exposure model for late, wrong, failed, partial, or unauditable processes.', progress: 0, sourceModel: 'canonical graph' },
    { id: '07', name: '07_Action_Backlog.csv', audience: 'Delivery teams', purpose: 'Ready-to-work modernization and remediation actions.', progress: 0, sourceModel: 'canonical graph' },
    { id: '08', name: '08_Evidence_Archive', audience: 'Audit / project team', purpose: 'Proof behind every finding.', progress: 0, sourceModel: 'canonical graph' },
    { id: '09', name: '09_Metadata_Manifest.json', audience: 'Automation / governance', purpose: 'Traceable metadata manifest for the full package.', progress: 0, sourceModel: 'canonical graph' }
  ],
  confidenceAreas: [
    { area: 'Source coverage', reviewed: 'Selected files, folders, exports, and extracts', coverage: 0, confidence: 0, blocked: 'Execute a source set to calculate coverage.' },
    { area: 'Extraction quality', reviewed: 'Readable text, workbook XML, document XML, SQL, scripts, and metadata', coverage: 0, confidence: 0, blocked: 'Binary formats may require native extractors or exported inventories.' },
    { area: 'Lineage depth', reviewed: 'Upstream and downstream source relationships', coverage: 0, confidence: 0, blocked: 'Lineage is generated after synthesis.' },
    { area: 'Action readiness', reviewed: 'Owners, priorities, dependencies, and acceptance criteria', coverage: 0, confidence: 0, blocked: 'Actions are generated after synthesis.' }
  ],
  failureRisks: [
    {
      id: 'RISK-001',
      scenario: 'Source set incomplete',
      impactedOutput: 'Discovery Action Pack',
      detection: 'Unresolved blockers or missing critical outputs',
      recovery: 'Add missing sources and re-execute synthesis',
      exposure: { low: 0, base: 0, high: 0, assumptions: 'Impact is source-specific.' },
      confidence: 70
    }
  ],
  backlog: [
    {
      actionId: 'ACT-001',
      title: 'Run analysis against the selected source set',
      owner: 'Discovery lead',
      priority: 'P0',
      dependency: 'Source files or folders selected',
      dueDate: 'Next run',
      acceptanceCriteria: 'The run returns canonical items, relationships, artifact outputs, and action records.',
      linkedItemId: 'SRC-001',
      mode: 'automate'
    }
  ],
  extractionCapabilities: [
    { source: 'Access', autoExtracts: ['ACCDB file metadata', 'exported object inventory', 'saved SQL exports', 'VBA exports'], currentStateOutputs: ['object inventory', 'dependency map', 'blocked extraction notes'], readiness: 60 },
    { source: 'Excel', autoExtracts: ['workbook metadata', 'sheets', 'shared strings', 'formula XML', 'connections', 'pivots', 'external links'], currentStateOutputs: ['formula register', 'refresh dependency hints', 'manual input candidates'], readiness: 88 },
    { source: 'Word', autoExtracts: ['document text', 'sections', 'comments', 'document properties'], currentStateOutputs: ['process narrative', 'rules', 'controls', 'open questions'], readiness: 84 },
    { source: 'Database', autoExtracts: ['SQL files', 'DDL exports', 'profiles', 'relationship hints'], currentStateOutputs: ['data dictionary', 'lineage nodes', 'lineage edges'], readiness: 82 },
    { source: 'Interview', autoExtracts: ['notes', 'tribal rules', 'owners', 'manual recovery paths'], currentStateOutputs: ['confidence gaps', 'decision log', 'blocked lineage branches'], readiness: 78 }
  ]
};

export const aiReadiness = {
  model: DISTILLERY_ENGINE_LABEL,
  contract: DISCOVERY_AGENT_CONTRACT,
  serverBoundary: 'The Distillery converts source evidence into normalized proof-graph deltas. The browser receives the distilled model only.'
};
